### ISSUE TITLE
Support for working directory

### ISSUE THREAD

**Issue by darkenmay** [n8maninger/action-golang-test#1]
Hello,

Thanks for awesome action. Is there any plan to add support for a working directory? Currently, there is no way to use the action for mono repo because go codebase resides in subdirectory.

**Comment by n8mgr** [comment]
An optional `working-directory` param has been added https://github.com/n8maninger/action-golang-test/releases/tag/v2.1.0

```yml
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: n8maninger/action-golang-test@v2
        with:
          working-directory: ./sub-directory
```
